apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: stampy-nlp-00030-zik
  namespace: '507517956350'
  selfLink: /apis/serving.knative.dev/v1/namespaces/507517956350/revisions/stampy-nlp-00030-zik
  uid: 7135e200-5319-44cc-97b6-267f61ccba44
  resourceVersion: AAX1lTkCEQ4
  generation: 1
  creationTimestamp: '2023-02-26T07:21:35.239128Z'
  labels:
    serving.knative.dev/route: stampy-nlp
    serving.knative.dev/configuration: stampy-nlp
    serving.knative.dev/configurationGeneration: '12'
    serving.knative.dev/service: stampy-nlp
    serving.knative.dev/serviceUid: 898f8218-fa09-4ac0-90bf-c8c3563819a7
    cloud.googleapis.com/location: us-west1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: ccstan99@gmail.com
    client.knative.dev/user-image: us-west1-docker.pkg.dev/stampy-nlp/cloud-run-source-deploy/stampy-nlp
    autoscaling.knative.dev/minScale: '1'
    autoscaling.knative.dev/maxScale: '10'
    run.googleapis.com/operation-id: b6f72052-f44b-4814-ba7e-84ebc12383d4
    run.googleapis.com/cpu-throttling: 'true'
  ownerReferences:
  - kind: Configuration
    name: stampy-nlp
    uid: d6c7dbd3-ca72-4581-ac54-dcf73ecd5798
    apiVersion: serving.knative.dev/v1
    controller: true
    blockOwnerDeletion: true
spec:
  containerConcurrency: 5
  timeoutSeconds: 300
  serviceAccountName: service@stampy-nlp.iam.gserviceaccount.com
  containers:
  - name: stampy-nlp-1
    image: us-west1-docker.pkg.dev/stampy-nlp/cloud-run-source-deploy/stampy-nlp@sha256:8150e3d0c0b08e0b0959b54e19ec0750ff105797eebcfdebff4161a1f8ab6ab7
    ports:
    - name: http1
      containerPort: 8080
    env:
    - name: PINECONE_API_KEY
      valueFrom:
        secretKeyRef:
          key: latest
          name: PINECONE_API_KEY
    - name: HUGGINGFACE_API_KEY
      valueFrom:
        secretKeyRef:
          key: latest
          name: HUGGINGFACE_API_KEY
    resources:
      limits:
        cpu: 2000m
        memory: 4G
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2023-02-26T07:22:13.213258Z'
  - type: Active
    status: 'True'
    lastTransitionTime: '2023-02-26T07:22:18.927773Z'
    severity: Info
  - type: ContainerHealthy
    status: 'True'
    lastTransitionTime: '2023-02-26T07:22:13.137194Z'
  - type: MinInstancesProvisioned
    status: 'True'
    lastTransitionTime: '2023-02-26T07:22:11.934522Z'
  - type: ResourcesAvailable
    status: 'True'
    lastTransitionTime: '2023-02-26T07:22:11.934522Z'
    severity: Error
  logUrl: https://console.cloud.google.com/logs/viewer?project=stampy-nlp&resource=cloud_run_revision/service_name/stampy-nlp/revision_name/stampy-nlp-00030-zik&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22stampy-nlp%22%0Aresource.labels.revision_name%3D%22stampy-nlp-00030-zik%22
  imageDigest: us-west1-docker.pkg.dev/stampy-nlp/cloud-run-source-deploy/stampy-nlp@sha256:8150e3d0c0b08e0b0959b54e19ec0750ff105797eebcfdebff4161a1f8ab6ab7
  containerStatuses:
  - name: stampy-nlp-1
    imageDigest: us-west1-docker.pkg.dev/stampy-nlp/cloud-run-source-deploy/stampy-nlp@sha256:8150e3d0c0b08e0b0959b54e19ec0750ff105797eebcfdebff4161a1f8ab6ab7
