name: Sync Coda to Pinecone Encodings
on:
  workflow_dispatch:
  schedule:
    - cron: "* 0 * * *"
env:
  FILEPATH: ./encode-faq-py/
  FILENAME: stampy-duplicates.json
  PROJECT_ID: stampy-nlp
  BUCKET_ID: stampy-nlp-resources
  CODA_TOKEN: ${{ secrets.CODA_TOKEN }}
jobs:
  encode-faq-py:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Clone Repository Code
      id: 'checkout'
      uses: 'actions/checkout@v3'
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 400.0.0'

    - name: 'Debugging Info with Cloud CLI'
      run: |
        gcloud info
        gcloud auth list
        gcloud config list
          
    - name: Generate FAQ Encodings and Upload to Pinecone Vector DB
      id: generate
      run: |
        cd ${{ env.FILEPATH }}
        pip install -q -r requirements.txt
        python3 encode-faq-titles.py

    - name: 'Upload Duplicates JSON to Cloud Bucket'
      id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '${{ env.FILEPATH }}${{ env.FILENAME }}'
        destination: '${{ env.BUCKET_ID }}'
