name: Sync Coda to Pinecone Encodings
on:
  workflow_dispatch:
  schedule:
    - cron: "* 0 * * *"
env:
  FILENAME: stampy-duplicates.json
  PROJECT_ID: stampy-nlp
  BUCKET_ID: stampy-nlp-resources
  CODA_TOKEN: ${{ secrets.CODA_TOKEN }}
  AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
jobs:
  encode-faq-py:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Clone Repository Code
      id: 'checkout'
      uses: 'actions/checkout@v3'
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Generate FAQ Encodings and Upload to Pinecone Vector DB
      id: generate
      run: /bin/bash encode-faq-titles.sh
